Api/urls.py
from django.conf.urls import url, include 
from . import views

from rest_framework_jwt.views import *

urlpatterns = [ 
	url(r'^$', views.index, name='Api.index'),
	url(r'^user/$', views.Users.as_view(), name='Api.user'),
	url(r'^codypen/', include('Api.codypen_urls')),

	url(r'^products/$', views.Produits.as_view(), name='Api.products'),
	url(r'^types/$', views.Types.as_view(), name='Api.types'),
	url(r'^associations/$', views.Associations.as_view(), name='Api.associations'),
	url(r'^achat/$', views.Achats.as_view(), name='Api.achats'),
	url(r'^reload/$', views.Reload.as_view(), name='Api.reload'),
	url(r'^history/$', views.History.as_view(), name='Api.history'),
	url(r'^categories/$', views.Categories.as_view(), name='Api.categories'),
	url(r'^miss_categorie/$', views.CategoriesMiss.as_view(), name='Api.categoriesMiss'),

	url(r'^api-auth/', include('rest_framework.urls')),
	url(r'^api-token-auth/', obtain_jwt_token),
	url(r'^api-token-refresh/', refresh_jwt_token),
	url(r'^api-token-verify/', verify_jwt_token),
]

Askip/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('Login.urls')),
    url(r'^manage/', include('Core.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include('Chat.urls')),
    url(r'^search/', include('Core.urls')),
    url(r'^clicker/', include('Clicker.urls')),
    url(r'^cotisation/', include('Cotisation.urls')),
    url(r'^moncompte/', include('Client.urls')),
    url(r'^comif/', include('Comif.urls')),
    url(r'^api/', include('Api.urls')),
    url(r'^codypen/', include('Codypen.urls')),


]

if settings.DEBUG:
    #import debug_toolbar
    urlpatterns = [
        #url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Cotisation/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='cotisation.index'),
    url(r'^modify/vote/(?P<association>.*)/(?P<vote>.*)/$', views.modify_vote, name='cotisation.modifyVote'),
    url(r'^modify/evennement/(?P<association>.*)/(?P<event>.*)/$', views.modify_event, name='cotisation.modifyEvent'),
    url(r'^modify/evennement/delete_description/$', views.delete_description_row, name='cotisation.delete_description'),
    url(r'^modify/action/(?P<association>.*)/$', views.action, name='cotisation.action'),
    url(r'^modify/(?P<association>.*)/(?P<cotisant>.*)/$', views.modify, name='cotisation.modify'),
    url(r'^club/(?P<association>.*)/(?P<club>.*)/$', views.modify_club, name='cotisation.modifyClub'),
    url(r'^reset/(?P<association>.*)/(?P<cotisant>.*)/$', views.reset, name='cotisation.reset'),
    url(r'^paye/(?P<association>.*)/(?P<cotisant>.*)/$', views.paye, name='cotisation.paye'),
    url(r'^genere/(?P<association>.*)/(?P<cotisant>.*)/$', views.generation, name='cotisation.generation'),
    url(r'^dashboard/(?P<association>.*)/$', views.dashboard, name='cotisation.dashboard'),
    url(r'^fiche/(?P<cotisant>.*)/$', views.fiche, name='cotisation.fiche-cotisation'),
    url(r'^hierarchie/(?P<association>.*)/$', views.hierarchie, name='cotisation.hierarchie'),
    url(r'^tresorerie/date/$', views.date, name='tresorerie.date'),
    url(r'^tresorerie/sujet/$', views.sujet, name='tresorerie.sujet'),
    url(r'^tresorerie/categorie/$', views.categorie, name='tresorerie.categorie'),
    url(r'^tresorerie/montant/$', views.montant, name='tresorerie.montant'),
    url(r'^tresorerie/moyen/$', views.moyen, name='tresorerie.moyen'),
    url(r'^event/startDate/$', views.start_date, name='cotisation.startDate'),
    url(r'^event/endDate/$', views.end_date, name='cotisation.endDate'),
    url(r'checkout/$', views.checkout, name='cotisation.checkout'),
    url(r'^modifyEventDate/$', views.modify_date_event_ajax, name='modifyEventDate'),
]

Login/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'login/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^$', views.index, name='login.index'),
]

"""url(r'^$', views.index, name='login.index'),
    url(r'^logout/$', views.logout, name='login.logout')"""

Cotisation/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User

from django.forms import ModelForm

from datetime import date

# Create your models here.

class Association(models.Model):
    nom = models.CharField(max_length = 100, primary_key = True, unique = True)
    # Security of the password is let to a person in the association
    mdp = models.CharField(max_length = 1000)
    logo = models.ImageField(upload_to="upload/", blank = True, null = True)
    prix_cotisation = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    description = models.TextField(null=True, blank=True)
    module_tresorerie = models.BooleanField(default = True)
    module_club = models.BooleanField(default = True)
    module_vote = models.BooleanField(default=True)
    module_evenement = models.BooleanField(default=True)
    module_vente = models.BooleanField(default=True)

    def __str__(self):
        return self.nom + " " + self.prix_cotisation.__str__()

    def gestionnaire_mdp(self):
        p = Poste.objects.none()
        for poste in Poste.objects.filter(association=self):
            if poste.gestionnaire_mdp:
                p = p | Poste.objects.filter(pk=poste.pk)
        return p

    def gestionnaire_tresorerie(self):
        p = Poste.objects.none()
        for poste in Poste.objects.filter(association=self):
            if poste.gestionnaire_tresorerie:
                p = p | Poste.objects.filter(pk=poste.pk)
        print(p)
        return p


class Annee(models.Model):
    nom = models.CharField(max_length = 10)

    def __str__(self):
        return self.nom


class Utilisateur(User):
    photo = models.ImageField(upload_to="upload/", blank = True)
    date_naissance = models.DateField()
    adresse = models.CharField(max_length=1000) 
    annee = models.ForeignKey(Annee)

    def __str__(self):
        return self.username


class Poste(models.Model):
    titre = models.CharField(max_length = 100)
    association = models.ForeignKey(Association)
    personne = models.ManyToManyField(Utilisateur, related_name = "poste", blank=True)
    candidat = models.ManyToManyField(Utilisateur, related_name="poste_candidat", blank=True)
    description = models.TextField(blank=True)
    ca = models.BooleanField(default = False)
    gestionnaire_mdp = models.BooleanField(default = False)
    gestionnaire_tresorerie = models.BooleanField(default = False)
    reader_tresorerie = models.BooleanField(default = False)

    def __str__(self):
        return format(self.association) + " " + self.titre + " " + format(self.personne.all())

    def create_hierachie(self):
        hierarchie = Hierarchie(poste = self)
        hierarchie.save()


class Cotisation(models.Model):
    association = models.ForeignKey(Association, related_name = "cotisant")
    personne = models.ForeignKey(Utilisateur)
    stade = models.IntegerField(default = 0)
    
    def __str__(self):
        return format(self.association) + " " + format(self.personne) + " " + format(self.stade)
    
    def poste(self):
        p = Poste.objects.none()
        poste_dispo = self.personne.poste.all()
        for poste_plausible in poste_dispo:
            if poste_plausible.association == self.association:
                p = p|Poste.objects.filter(pk=poste_plausible.pk) #On somme que des queryset et pas des objets
        return p
        

class Club(models.Model):
    nom = models.CharField(max_length = 100, primary_key = True, unique = True)
    logo = models.ImageField(upload_to="upload/", blank = True, null = True)
    prix_cotisation = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    association = models.ForeignKey(Association, related_name="club")
    administrateurs = models.ManyToManyField(Cotisation)
    description = models.TextField()

    def __str__(self):
        return "Club " + self.nom + " de l'association " + self.association.nom


class Hierarchie(models.Model):
    poste = models.OneToOneField(Poste, related_name="poste", unique=True)
    fils = models.ManyToManyField(Poste, related_name="fils", blank=True)

    def __str__(self):
        return format(self.poste)


class Depense(models.Model):
    association = models.ForeignKey(Association)
    date = models.DateField(default = date.today)
    sujet = models.CharField(max_length=100, blank = True, null = True)
    commentaire = models.TextField(blank=True, null=True) 
    montant = models.DecimalField(max_digits=10, decimal_places=2)
    categorie = models.CharField(max_length=100)
    moyen = models.CharField(max_length=100, blank=True, null=True)
    modifier = models.ForeignKey(Utilisateur, null=True, blank=True)

    def __str__(self):
        return format(self.association) + " " + self.sujet + " " + format(self.montant)


class Reponse(models.Model):
    reponse = models.TextField()
    nb_reponse = models.IntegerField(default = 0)

    def __str__(self):
        return self.reponse


class Vote(models.Model):
    association = models.ForeignKey(Association)
    accessibility = models.IntegerField(default = 0) # 0 = All; 1 = Prive; 2 = Restreint
    startDate = models.DateTimeField()
    endDate = models.DateTimeField()
    question = models.TextField()
    reponse = models.ManyToManyField(Reponse)
    user_answered = models.ManyToManyField(Utilisateur)

    def __str__(self):
        return self.question
    
    def user(self):
        if self.accessibility == 0:
            return Utilisateur.objects.all()
        elif self.accessibility == 1:
            return Cotisant.objects.filter(association = self.association)
        elif self.accessibility == 2:
            users = Utilisateur.objects.none()
            postes = Poste.poste(self.association)

            for poste in postes:
                if poste.ca:
                    users = users | poste.personne.all()
            return users.distinct()


class Evenement(models.Model):
    nom = models.CharField(max_length=100)
    association = models.ForeignKey(Association, related_name="evenement")
    description = models.TextField(blank = True)
    photo = models.ImageField(upload_to="upload/", blank = True, null = True)
    startDate = models.DateTimeField(blank=True, null=True, unique=True)
    endDate = models.DateTimeField(blank=True, null=True, unique=True)
    prix = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    nombre_place = models.IntegerField(default = 0)
    cotisant = models.BooleanField(default = False)
    participant = models.ManyToManyField(Utilisateur, blank=True, related_name="evenementParticipe")
    candidat = models.ManyToManyField(Utilisateur, blank=True)

    def __str__(self):
        return self.nom + "   " + format(self.prix) + "E"

    def is_full(self):
        return len(self.participant.all()) >= self.nombre_place
    
    def can_participate(self, user):
        if not self.cotisant:
            return True
        else:
            for elt in self.association.cotisant:
                if elt.personne == user:
                    return True
            return False

    def add(self, user):
        if not self.is_full() or self.nombre_place == 0:
            self.participant.add(user)
            self.save()
            return True
        else:
            return False


class RowDescriptionException(Exception):
    def __init__(self, value):
        self.value = "RowDescriptionException raised : " + format(value)

    def __str__(self):
        return self.value


class ImageDescription(models.Model):
    image = models.ImageField(upload_to="upload/", blank=True, null=True)
    position = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return "Image en position : " + format(self.position)

    def save(self):
        if self.position in ['centre', 'gauche', 'droite']:
            super(ImageDescription, self).save()
        else:
            raise RowDescriptionException('The position of the image shall be nothing, centre, gauche or droite')


class TextDescription(models.Model):
    text = models.TextField()
    position = models.CharField(max_length=10, blank=True, null=True)
    fontsize = models.IntegerField(default=15)
    fontalign = models.CharField(default="left", max_length=10)
    padding_top = models.IntegerField(default=20)
    padding_bottom = models.IntegerField(default=20)
    padding_left = models.IntegerField(default=20)
    padding_right = models.IntegerField(default=20)

    def __str__(self):
        return format(self.text)

    def save(self):
        if self.position in ['centre', 'gauche', 'droite']:
            super(TextDescription, self).save()
        else:
            raise RowDescriptionException('The position of the text shall be nothing, centre, gauche or droite')


class RowDescription(models.Model):
    nombre_case = models.IntegerField(default=0)
    disposition_case = models.CharField(max_length=10, null=True, blank=True)
    images = models.ManyToManyField(ImageDescription, blank=True)
    texts = models.ManyToManyField(TextDescription, blank=True)
    fusion = models.BooleanField(default=False)
    position = models.IntegerField()

    def save(self, *args, **kwargs):
        if (
                int(self.nombre_case) <= 3 and
                (
                    self.disposition_case in ['', 'droite', 'gauche', 'centre'] or
                    not self.disposition_case
                )
        ):
            super(RowDescription, self).save(*args, **kwargs)
        else:
            raise RowDescriptionException('At least one parameter is not correct.')

    def delete(self):
        for text in self.texts.all():
            text.delete()
        for image in self.images.all():
            image.delete()

        position = self.position
        rows = RowDescription.objects.all().order_by('position')
        for row in rows:
            if row.position > position:

Login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User

from django.forms import ModelForm, Textarea

class UserModel(models.Model):
    tag = models.IntegerField(default = 0)
    user = models.OneToOneField(User)

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

# Create your models here.

Login/forms.py
from django import forms

class UserForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)


    

Login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect

from django.utils import timezone

from .models import UserForm

from django.contrib.auth.models import User


# Create your views here.

def index(request):
    if request.user.is_authenticated:
        return redirect('chat.index', permanent=True)
    else:
        return redirect("/login/", permanent=True)
        

def signIn(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = UserForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            request.session.set['username'] = "BOB"
            request.session.set_expiry(SESSION_EXPIRE_AT_BROWSER_CLOSE=True)
            
            return render(request, "login/thanks.html", locals())

    # if a GET (or any other method) we'll create a blank form
    else:
        form = UserForm()
    return render(request, "login/index.html", locals())


def logout(request):
    request.session.flush()
    request.session['actif'] = False
    request.session.save()

    return redirect('login.index', permanent = True)

Cotisation/templates/cotisation/login.html
{% extends 'base.html' %}
{% load tags static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/cotisation.css' %}" />

{% endblock %}

{%block header%}
    {% include "header.html" with active_tab="Associatif"%}
{%endblock%}
{% block content %}

{% if error %}
    <div class="alert alert-warning alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Erreur !</strong> {{ error.0 }}
        </div>
{% endif %}
<center>
<form method="post">
    {%csrf_token%}  
    <div class="form-group">
        <select name="association" class="form-control" id="association" style="width:25%; transform:translate(0px, -7px);">
            <option value="NC">Association</option>
            {%for association in associations%}
            <option value="{{association.nom}}">{{association.nom}}</option>
            {%endfor%}
        </select>
    </div>
    <div class="form-group">
        <input style="width:25%;" class="form-control" type="password" name="password" required>
    </div>

    <button type="submit" class="btn btn-primary">Valider</button>
</form>
</center>
{%endblock%}

Cotisation/templates/cotisation/parametre.html
<div id="parametre" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <center><h4 class="modal-title">Parametres</h4></center>
            </div>
            <div class="modal-body">
                <form method="post" action="">
                    {%csrf_token%}
                    <input type="hidden" name="parametre" value="1">
                    <div class="form-group">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <label class="form-label">Ancien mot de passe</label>
                                    <input class="form-control"type="password" name="old_mdp">
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <label class="form-label">Nouveau mot de passe</label>
                                    <input class="form-control"type="password" name="new_mdp">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="container-fluid">
                            <div class="row" id="tresorier">
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <label for="" class="form-label">Gestion tésorerie</label><strong style="padding-left:30px;"onclick="addTresorier()">Ajouter un trésorier*</strong>
                                    <select class="form-control tresorier" name="gestion_treso_0">
                                        {%for poste in association.poste_set.all%}
                                        <option value="{{poste.pk}}">{{poste.titre}}</option>
                                        {%endfor%}
                                    </select>
                                    
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="form-group">
                        <div class="container-fluid">
                            <div class="row" id="mdp">
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <label for="" class="form-label gestion_mdp">Gestion mot de passe</label><strong style="padding-left:30px;"onclick="addMdp()">Ajouter un gestionnaire des mdp*</strong>
                                    <select class="form-control mdp" name="gestion_mdp_0">
                                        {%for poste in association.poste_set.all%}
                                        <option value="{{poste.pk}}">{{poste.titre}}</option>
                                        {%endfor%}
                                    </select>
                                    
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="container-fluid">
                            <div class="row" id="deltreso">
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <label for="" class="form-label supprime_treso">Enlever droit trésorerie</label><strong style="padding-left:30px;"onclick="delTreso()">Supprimer un autre</strong>
                                    <select class="form-control deltreso" name="supprime_droit_treso_0">
                                        <option value="NULL">Poste</option>
                                        {%for poste in association.gestionnaire_tresorerie%}
                                        <option value="{{poste.pk}}">{{poste.titre}}</option>
                                        {%endfor%}
                                    </select>
                                    
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="container-fluid">
                            <div class="row" id="delmdp">
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <label for="" class="form-label supprime_mdp">Enlever droit mdp</label><strong style="padding-left:30px;"onclick="delMdp()">Supprimer un autre</strong>
                                    <select class="form-control delmdp" name="supprime_droit_mdp_0">
                                        <option value="NULL">Poste</option>
                                        {%for poste in association.gestionnaire_mdp%}
                                        <option value="{{poste.pk}}">{{poste.titre}}</option>
                                        {%endfor%}
                                    </select>
                                    
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="container-fluid">
                            <div class="row" id="delmdp">
                                <div class="col-md-3 col-sm-3 col-xs-6">
                                    <label for="" class="form-label">Module Trésorerie</label>
                                    <input style="float:right;" type="checkbox" {%if association.module_tresorerie%}checked{%endif%} name="module_treso" value="{{association.pk}}">
                                </div>
                                <div class="col-md-3 col-sm-3 col-xs-6">
                                    <label for="" class="form-label">Module Club</label>
                                    <input style="float:right;" type="checkbox" {%if association.module_club%}checked{%endif%} name="module_club" value="{{association.pk}}">
                                </div>
                                <div class="col-md-3 col-sm-3 col-xs-6">
                                    <label for="" class="form-label">Module Vote</label>
                                    <input style="float:right;" type="checkbox" {%if association.module_vote%}checked{%endif%} name="module_vote" value="{{association.pk}}">
                                </div>
                                <div class="col-md-3 col-sm-3 col-xs-6">
                                    <label for="" class="form-label">Module Evénement</label>
                                    <input style="float:right;" type="checkbox" {%if association.module_evenement%}checked{%endif%} name="module_event" value="{{association.pk}}">
                                </div>
                                <div class="col-md-3 col-sm-3 col-xs-6">
                                    <label for="" class="form-label">Module Vente</label>
                                    <input style="float:right;" type="checkbox" {%if association.module_vente%}checked{%endif%} name="module_vente" value="{{association.pk}}">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="container-fluid" >
                            <label class="form-label">Description de l'association (Markers HTML autorisés)</label>
                            <textarea class="form-control" rows=20 name="description">{{association.description}}</textarea>
                        </div>
                    </div>
    

                    <div class="form-group">
                        <center>
                            <button type="submit" class="btn btn-default">Valider</button>
                        </center>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <p>*Trésorier : personne qui aura le droit de modifier la trésorerie de l'association</p>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

Cotisation/templates/cotisation/poste.html
{% load static cotisant_tags%}
<div class="row module" id="postes">
    <a style="font-weight:bold;display:none;" id="newPosteBtn" data-toggle="modal" data-target="#nouveau_poste">Nouveau Poste</a><br>
    <form method="post" action="{%url 'cotisation.action' association=association.nom%}">
        {%csrf_token%}
    
        <table style="width:100%;" class="table table-striped poste">
            <thead>
                <tr>
                    <th style="width:20px;"><input id="master_poste" type="checkbox" value="TOUS"></th>
                    <th>Intitule</th>
                    <th>Description</th>
                    <th>En poste</th>
                    <th>Candidat</th>
                    <th>CA</th>
                    <th>Lecture tresorerie</th>
                </tr>
            </thead>
            <tbody>
                {%for poste in association.poste_set.all%}
                <tr>
                    <th style="width:20px;"><input type="checkbox" name="poste_check_{{poste.pk}}" class="poste_check" value="{{poste.pk}}"></th>
                    <th>{{poste.titre}}</th>
                    <th>{{poste.description}}</th>
                    <th>
                        {%for poste_user in poste.personne.all%}
                        {{poste_user.first_name}} {{poste_user.last_name}} <br>
                        {%endfor%}
                    </th>
                    <th>
                        {%for poste_user in poste.candidat.all%}
                        {{poste_user.first_name}} {{poste_user.last_name}} <br>
                        {%endfor%}
                    </th>
                    <th><input type="checkbox"{%if poste.ca%}checked{%endif%} onclick="return false;"></th>
                    <th><input type="checkbox"{%if poste.reader_tresorerie%}checked{%endif%} name="read_treso_{{poste.pk}}" value="{{poste.pk}}"></th>
                </tr>
            
                {%endfor%}
            </tbody>
        </table>
        <br>
        <div class="form-group">
            <div class="container">
                <div class="col-md-1 col-sm-3 col-xs-3">
                    <label for="action">Action</label>
                </div>
                <div class="col-md-3 col-sm-5 col-xs-5">
                    <input type="hidden" name="action_poste" value="NULL">
                    <select name="action" class="form-control" id="action" style="transform:translate(0px, -7px);">
                        <option value="1">Supprimer</option>
                        <option value="2">Ajouter/Enlever au CA</option>
                        <option value="3">Ajouter/Enlever droit lecture trésorerie</option>
                    </select>
                </div>
                <div class="col-md-2 col-md-offset-1 col-sm-3 col-sm-offset-1 col-xs-3 col-xs-offset-1">
                    <button style="transform:translate(0px, -7px);" type="submit" class="btn btn-primary">Valider</button>
                </div>
            </div>
        </div>
    </form>

    <div id="nouveau_poste" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <center>
                        <h4 class="modal-title">Nouveau Poste</h4>
                    </center>
                </div>
                <div class="modal-body">
                    <form method="POST">
                        {%csrf_token%}
                        <div class="form-group" id="titre_form">
                            <label for="titre">Nom du poste</label>
                            <input style="color:#000000;" type="text" class="form-control" max_length="100" id="poste_titre" name="poste_titre" required/>
                        </div>
                        <div class="form-group">
                            <label for="" class="form-label">Est au ca ?</label>
                            <input type="checkbox" name="ca" value="1">
                        </div>

                        <div class="form-group">
                            <label for="" class="form-label"></label>
                            <textarea name="description" class="form-control"></textarea>
                        </div>

                        <button class="btn btn-primary" type="submit">Valider</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>